{% set name = "schnetpack" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8db2224364760ad0a0fc58efe89078df7754e17e21afa88d958f2cce87c95da4

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}  # pytorch is currently incompatible to dataclasses in 3.11
    - pip
  run:
    - python >={{ python_min }},<3.11  # pytorch is currently incompatible to dataclasses in 3.11
    - pip
    - pytorch >=1.1.0
    - numpy
    - ase >=3.18
    - h5py
    - tensorboardx
    - tqdm
    - pyyaml
    - sympy <=1.12
    - matscipy
    - dirsync
    - fasteners
    - pytorch-lightning
    - omegaconf
    - torch-ema
    - hydra-colorlog
    - hydra-core
    - rich
    - black
    - pre-commit
    - tensorboard

test:
  requires:
    - python {{ python_min }}
  imports:
    - schnetpack
  commands:
    - pip check

about:
  home: https://github.com/atomistic-machine-learning/schnetpack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SchNetPack - Deep Neural Networks for Atomistic Systems

  description: |
    SchNetPack aims to provide accessible atomistic neural networks 
    that can be trained and applied out-of-the-box, while still being 
    extensible to custom atomistic architectures.
  doc_url: https://schnetpack.readthedocs.io/
  dev_url: https://github.com/atomistic-machine-learning/schnetpack

extra:
  recipe-maintainers:
    - jan-janssen
    - ktschuett
