{% set name = "schnetpack" %}
{% set version = "2.2.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28379cc38516f5112faa1f484c9102487855bc2c4a7a03c89997c2a6145f8519

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=2.0.0
    - sympy >=1.13
    - ase >=3.21
    - h5py
    - pyyaml
    - hydra-core >=1.1.0
    - pytorch >=2.5.0
    - pytorch_lightning >=2.0.0
    - torchmetrics
    - hydra-colorlog >=1.1.0
    - rich
    - fasteners
    - dirsync
    - torch-ema
    - matscipy >=1.1.0
    - tensorboard >=2.17.1
    - tensorboardx >=2.6.2.2
    - tqdm
    - pre-commit
    - black
    - protobuf
    - progressbar
    - pytest
    - petname
    - python-vesin

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - schnetpack
  commands:
    - pip check

about:
  home: https://github.com/atomistic-machine-learning/schnetpack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SchNetPack - Deep Neural Networks for Atomistic Systems

  description: |
    SchNetPack aims to provide accessible atomistic neural networks 
    that can be trained and applied out-of-the-box, while still being 
    extensible to custom atomistic architectures.
  doc_url: https://schnetpack.readthedocs.io/
  dev_url: https://github.com/atomistic-machine-learning/schnetpack

extra:
  recipe-maintainers:
    - jan-janssen
    - ktschuett
