{% set name = "schnetpack" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f873608cbcb2b2d4bc8bea17a900ff3db9469ee859c9a9096b77e017d1fa80a6

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pytorch-cpu >=0.4.1
    - numpy
    - ase >=3.18
    - h5py
    - tensorboardx
    - tqdm
    - pyyaml

test:
  imports:
    - schnetpack

about:
  home: https://github.com/atomistic-machine-learning/schnetpack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SchNetPack - Deep Neural Networks for Atomistic Systems'

  description: |
    SchNetPack aims to provide accessible atomistic neural networks 
    that can be trained and applied out-of-the-box, while still being 
    extensible to custom atomistic architectures.
  doc_url: https://schnetpack.readthedocs.io/
  dev_url: https://github.com/atomistic-machine-learning/schnetpack

extra:
  recipe-maintainers:
    - jan-janssen
    - ktschuett
