schema_version: 1

context:
  name: schnetpack
  version: "2.2.0"
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 28379cc38516f5112faa1f484c9102487855bc2c4a7a03c89997c2a6145f8519

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy >=2.0.0
    - sympy >=1.13
    - ase >=3.21
    - h5py
    - pyyaml
    - hydra-core >=1.1.0
    - pytorch >=2.5.0
    - pytorch-lightning >=2.0.0
    - torchmetrics
    - hydra-colorlog >=1.1.0
    - rich
    - fasteners
    - dirsync
    - torch-ema
    - matscipy >=1.1.0
    - tensorboard >=2.17.1
    - tensorboardx >=2.6.2.2
    - tqdm
    - pre-commit
    - black
    - protobuf
    - progressbar
    - pytest
    - petname
    - python-vesin

tests:
  - python:
      imports:
        - schnetpack
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: MIT
  license_file: LICENSE
  summary: SchNetPack - Deep Neural Networks for Atomistic Systems
  description: |
    SchNetPack aims to provide accessible atomistic neural networks
    that can be trained and applied out-of-the-box, while still being
    extensible to custom atomistic architectures.
  homepage: https://github.com/atomistic-machine-learning/schnetpack
  repository: https://github.com/atomistic-machine-learning/schnetpack
  documentation: https://schnetpack.readthedocs.io/

extra:
  recipe-maintainers:
    - jan-janssen
    - ktschuett
