travis:
  secure:
    BINSTAR_TOKEN: QVcZ2gNDFAnq9m9yvNVGEE6sAtQNRxr43RYdgkEP50wMzIbTaMLrWtsATv0/3yBVhqfSA1eO3zAHe6pFBBhvXdBLd5vmtBpUD0subtArh+QCjzDEzmkiEHLWRs99WDVujlm0x+zpU1zASNxmb4tfoJhxgTYkrlRFaoSOSvUGlID4ZTOIWKQlX98/ktNjGPx38XWVUV8QbwmpFvhoLELl+/uVJiFInMhaDzXMA6PamSef+c+o9mkk+scEyLgathwpMaSNpevPUW4f2V7NHlHI4AAM5J3FYU6ytMbDtAWJ7c1HE7jACDX9yp0hpzPIuUMjQ0Nx95ROougd5PRvJH+sYyLDsavy9suxscfuJvk6mR5sRa69lfyu8cS4CNYDON3+liNexcTgnjcCcPPz/K2BGByv4Nd9roATOFhWIKp+bYQE/eIkVykhcXmmQQM3zBO5gSp5+ntwgK+aDhoC0H+W2r+P0r09Iuogh5PtXX/zhf4NTZm0L5tXwukW6ZPTwhz48Q9TjRC0eTf9ta78z1BJLPszg7o+36hLTGTQT6QfLbDRNrpEYNBqHQ+wZdTIbGqmnwc3l7Azdl2at4altin0yhELgAwmg0Wa2szIE1AR8aMAgZI7qfeN8x104VG9b81CRjcVS4+Itt/VemSk2uzwiN7823rAHg63/VFrv/rrrR0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
